= Auto-pairing of characters

Auto-pairing of characters.

:vs-code: https://code.visualstudio.com

Heavily based on {vs-code}[Visual Studio Code].

== Usage

Enter `enable-auto-pairs` to enable auto-pairing of characters.

== Configuration

--------------------------------------------------------------------------------
set-option global auto_pairs ( ) { } [ ] '"' '"' "'" "'" ` ` “ ” ‘ ’ « » ‹ ›
--------------------------------------------------------------------------------

== How does it work?

The script installs insert hooks on opening pair characters, such as brackets and quotes.

When auto-closing has been triggered, it activates the following functionalities:

- `closing-pair` ⇒ Insert closing pair or move right in pair
- `Enter` ⇒ Insert a new indented line in pair (only for the next key)
- `Control+Enter` ⇒ Prompt a count for new indented lines in pair (only for the next key)

When moving or leaving insert mode, the functionalities deactivate.

=== Technical details

- Insert hooks are added on opening pair characters from `auto_pairs` option.
- Evaluates `auto_close_trigger` option to activate auto-pairing.
- Provides `opening_pair` expansion in expressions.
- Uses `inserted_pairs` count to keep track of inserted pairs for inserting or moving in pair.
- Uses the same implementation for nestable (such as brackets) and non-nestable (such as quotes) pairs.
Since insert hooks are added on opening pair characters (for auto-pairing) and mappings on closing pair characters (for moving in pair),
we can distinguish same pair characters once auto-pairing has been activated.

== Commands

- `enable-auto-pairs`
- `disable-auto-pairs`

== Options

- `auto_pairs`
